### ISSUE TITLE
examples where GO linkout results do not match claim name 

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/dgi-db#162]
Related to issue #69 and PR #157 

Here's just a few cases where the name associated with a gene claim we pulled from GO does not turn up a clear match in the search result we're linking out to. I couldn't find an example of this for a grouped gene claim and most of the ungrouped claims I checked were examples that did not match.

gene_claims.id = 337a327e-d338-4fbc-8516-cec8165cffb1

http://amigo.geneontology.org/amigo/search/bioentity?fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22&q=HEL-S-31

gene_claims.id = 0806f086-47a3-4b03-8e03-ce12a43bb61d

http://amigo.geneontology.org/amigo/search/bioentity?fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22&q=DKFZp686M1669

 gene_claims.id = fd9c306c-7c1b-4326-8a83-90093c21e818

http://amigo.geneontology.org/amigo/search/bioentity?fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22&q=FLJ90650

**Comment by susannasiebert** [comment]
I'm not sure why this issue was assigned to me. Since these are claims, not groups, the names were added like this during the original import. We should check the original GO import spreadsheet, if we still have it, to double-check where these names are coming from. If these names/claims don't exist in GO anymore, we could consider deleting them.

**Comment by ahwagner** [comment]
Hey @susannasiebert. I forgot to comment here, but @kcotto investigated and found that these claims do not exist in GO anymore. This is the sort of thing that should be resolved automatically by #148, but I agree with the need to delete these if the automatic updates are a long way off.

**Comment by kcotto** [comment]
Was looking into this issue this morning and the GO linkouts appear to be completely broken.

**Comment by kcotto** [comment]
So it looks like we are not pulling from `amigo.geneontology.org` but rather `http://golr.geneontology.org/select?` instead. I think the fix for this would be changing the base url in the importer to `http://amigo.geneontology.org/amigo/search/bioentity?fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22&q=`

**Comment by susannasiebert** [comment]
Yes, that should work. I need to double check all the other sources that were updated and make sure that this didn't cause problems elsewhere. I didn't realize the base_irl was used for that purpose.

@ahwagner should I just ssh into production and change the base URL for GO in the production database, as well as make a PR to change the importer?
