### ISSUE TITLE
Check that the new interaction score gets included in the interaction TSV

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#458]

**Comment by acoffman** [comment]
I looked into this. We generate a TSV for the interaction claims, not the interactions (interaction groups) themselves. The groups are the things with a score, not the claims. Do we want to include the score for an interaction's group if it has one even though its not from the same entity as the TSV row represents?

@ahwagner

**Comment by ahwagner** [comment]
Because each claim record also includes the grouped gene and drug concepts I think we can, but should make it clear that it applies to the group, not the individual claim. Perhaps with a field header of Interaction_Group_Score or similar.

In records where the drug claim does not have a drug group (and therefore no interaction group or score), this field would be blank.
