### ISSUE TITLE
Are all entries of interest reflected in database?

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#93]
Christopher Southan from Guide To Pharmacology reports:

> For example our BACE1 entry http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=2330 . We have 15 to your 11 (possibly a release issue).  Also DrugBank http://www.drugbank.ca/biodb/polypeptides/P56817 has 28 chemistry mappings vs your 8.   For BACE2 the difference is also 5 vs 8 our side.

We should review our filtering and curation steps, and make sure that these results match our expectations for the content that we want in DGIdb.

**Comment by cdsouthan** [comment]
Hi, I suspect there is also an issue with the PubMed mappings and the scoring heuristic.  The DrugBank entries are scored up because the PubMed links were parsed - but most have the identical reference to PDB per se (since that is where nearly all the research compounds were pulled from.  On the other hnd the Guide to PHARMACOLOGY (GtoPdb) entries actually have uniquely mapped PMIDs related to the activty, but these links were not parsed - hence we get scored down  :(

**Comment by malachig** [comment]
@cdsouthan, this is a great point and I completely agree.  Getting these links parsed will give more complete results, and as you say improve the scoring to more accurately reflect all the curation effort that has gone into some of these GTP entries.

**Comment by susannasiebert** [comment]
I know this is an older issue but digging into this a bit it looks like these are cases where DGIdb is unable to group the drug concept. In the UI Interactions will only be available if the drug was grouped. The underlying interaction claims do exist in the database, even if the drug concept is ungrouped and those appear to match the counts available in the underlying source. For Guide To Pharmacology we are now also parsing the PMIDs. I believe this issue can be closed.
